apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev
    version: "1.0"
  name: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dev
    spec:
      containers:
        - name: dev
          image: 26ka/car_service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dev
  name: dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8181
      name: http
  selector:
    app: dev
  type: LoadBalancer
status:
  loadBalancer: {}