apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: car-service
    version: "1.0"
  name: car-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: car-service
    spec:
      containers:
        - name: carservice
          image: 26ka/car_service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: car-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: car-service
  type: LoadBalancer

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microservice-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: car-service
spec:
  hosts:
    - "*"
  gateways:
    - microservice-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: car-service.default.svc.cluster.local
            port:
              number: 80